# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      npm i -g @nestjs/cli
      sudo apt install sqlite3
    init: yarn install # runs during prebuild
    command: |
      gp env DATABASE_URL="file:./dev.db"
      yarn start:dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: ignore

vscode:
  extensions:
    - bierner.emojisense
    - dracula-theme.theme-dracula
    - dbaeumer.vscode-eslint
    - mhutchie.git-graph
    - codezombiech.gitignore
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - TabNine.tabnine-vscode
    - rangav.vscode-thunder-client
    - qcz.text-power-tools
    - PKief.material-icon-theme
    - Prisma.prisma
