# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      npm i -g @nestjs/cli
      sudo apt install sqlite3
    init: yarn install # runs during prebuild
    command: |
      yarn start:dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: ignore
