---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: test:e2e
    before: |
      npm i -g @nestjs/cli dotenv-cli
      sudo apt install sqlite3
    init: |  # runs during prebuild
      yarn install
      gp sync-done install
    command: |
      yarn test:e2e
  - name: test:unit
    init: |
      gp sync-await install
    command: |
      yarn test:watch
  - name: start:dev
    init: |
      gp sync-await install
    command: |
      yarn start:dev
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: ignore

vscode:
  extensions:
    - bierner.emojisense
    - dracula-theme.theme-dracula
    - dbaeumer.vscode-eslint
    - mhutchie.git-graph
    - codezombiech.gitignore
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - TabNine.tabnine-vscode
    - rangav.vscode-thunder-client
    - qcz.text-power-tools
    - PKief.material-icon-theme
    - Prisma.prisma
    - Orta.vscode-jest
    - eamodio.gitlens
